apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: user-service
  type: ClusterIP